import { db } from "./index";
import { products } from "./schema";

const productData = [
  {
    name: "Alite Foaming Face Wash 120ml | Best for Clear Skin | Active Acne Control | Deep Cleansing Face Cleanser for Men & Women | Tan Removal & Oil Control",
    description: "Deep cleansing face wash that removes tan, controls oil, and fights acne. Suitable for both men and women.",
    originalPrice: "500.00",
    price: "495.00",
    discountPercentage: 1,
    sku: "ALITE-FW-120ML",
    category: "face-care" as const,
    stock: 50,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/FoamingFacewash_01_533x.jpg?v=1741151278",
    isBestSeller: true,
  },
  {
    name: "Alite Anti Acne Facewash 140g - Prevent Acne Breakouts & Control Oily Skin",
    description: "Prevents acne breakouts and controls oily skin. Formulated for acne-prone skin.",
    originalPrice: "500.00",
    price: "495.00",
    discountPercentage: 1,
    sku: "ALITE-AAF-140G",
    category: "face-care" as const,
    stock: 45,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/AliteAntiAcneFacewash_Listing01_2e6b79f5-2edd-4efa-b6c7-ac714f803f50_533x.jpg?v=1741150509",
    isBestSeller: true,
  },
  {
    name: "Alite Spot Reduction Cream 30 gm - Remove Acne Scars, Dark Spots, Pigmentation with Pea & Seed Extract",
    description: "Reduces acne scars, dark spots, and pigmentation with natural pea and seed extracts.",
    originalPrice: "500.00",
    price: "495.00",
    discountPercentage: 1,
    sku: "ALITE-SRC-30GM",
    category: "face-care" as const,
    stock: 30,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/SpotHealingCream-01_533x.jpg?v=1740470824",
    isBestSeller: true,
  },
  {
    name: "Alite Anti Acne Gel 30 gm | Fast Action on Acne, Pimples | Treats, Repairs, Prevents Acne",
    description: "Fast-acting gel that treats, repairs, and prevents acne and pimples.",
    originalPrice: "500.00",
    price: "495.00",
    discountPercentage: 1,
    sku: "ALITE-AAG-30GM",
    category: "face-care" as const,
    stock: 40,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/AliteAntiAcneGel_01_533x.jpg?v=1740470680",
    isBestSeller: true,
  },
  {
    name: "Alite Anti Acne Soap – Clears Body Acne, Fades Acne Marks & Removes Dead Skin | Tea Tree Oil & Vitamin E | Pack of 5",
    description: "Clears body acne, fades marks, and removes dead skin. Enriched with Tea Tree Oil and Vitamin E. Pack of 5.",
    originalPrice: "375.00",
    price: "369.00",
    discountPercentage: 2,
    sku: "ALITE-AAS-PACK5",
    category: "body-care" as const,
    stock: 60,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/AliteantiacneSoapListing3_533x.png?v=1738751939",
    isBestSeller: true,
  },
  {
    name: "Alite Oil Control Face Wash 140g, For Oily & Acne-Prone Skin, Detan and Oil Control",
    description: "Specially formulated for oily and acne-prone skin. Controls oil and removes tan.",
    originalPrice: "350.00",
    price: "345.00",
    discountPercentage: 1,
    sku: "ALITE-OCFW-140G",
    category: "face-care" as const,
    stock: 55,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/oilcontrol_01_533x.jpg?v=1741150794",
    isBestSeller: false,
  },
  {
    name: "ALITE NEEM & ALOEVERA FACE WASH 140g",
    description: "Gentle face wash with Neem and Aloe Vera extracts for healthy, glowing skin.",
    originalPrice: "200.00",
    price: "195.00",
    discountPercentage: 3,
    sku: "ALITE-NAFW-140G",
    category: "face-care" as const,
    stock: 70,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/ALITE_NEEM_ALOE_Face_Wash_1_533x.jpg?v=1735631539",
    isBestSeller: false,
  },
  {
    name: "Alite Neem Glow Scrub 140gm | Radiant & Bright Skin | Complexion Boost Formula",
    description: "Exfoliating scrub that brightens skin and boosts complexion. Formulated with Neem extracts.",
    originalPrice: "300.00",
    price: "295.00",
    discountPercentage: 2,
    sku: "ALITE-NGS-140GM",
    category: "face-care" as const,
    stock: 35,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/Neem_Scrub_Listing_2_533x.png?v=1739874843",
    isBestSeller: false,
  },
  {
    name: "Alite hair removal cream 60gm",
    description: "Gentle hair removal cream for smooth, hair-free skin. Suitable for sensitive skin.",
    originalPrice: "200.00",
    price: "180.00",
    discountPercentage: 10,
    sku: "ALITE-HRC-60GM",
    category: "body-care" as const,
    stock: 25,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/Alite_Skin_hair_removal_Women_1_533x.jpg?v=1735631500",
    isBestSeller: false,
  },
  {
    name: "Alite hair removal cream (men) 120g",
    description: "Hair removal cream specially formulated for men. Removes hair quickly and effectively.",
    originalPrice: "250.00",
    price: "245.00",
    discountPercentage: 2,
    sku: "ALITE-HRC-MEN-120G",
    category: "body-care" as const,
    stock: 30,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/Hair_removal_cream_Men-1_533x.png?v=1735631519",
    isBestSeller: false,
  },
  {
    name: "Acne-Free Glowing Combo Prevent Acne, Pimples & Control Oily Skin | Treats, Repairs, Prevents Acne",
    description: "Complete acne care combo including face wash and gel. Prevents, treats, and repairs acne.",
    originalPrice: "500.00",
    price: "495.00",
    discountPercentage: 1,
    sku: "ALITE-COMBO-ACNE",
    category: "combo" as const,
    stock: 20,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/AntiAcneFacewash_AcneGelCombo_533x.jpg?v=1732618474",
    isBestSeller: false,
  },
  {
    name: "Alite Charcoal Face Wash | Deep Cleansing | Pore Minimizing | Oil Control",
    description: "Charcoal-infused face wash that deeply cleanses, minimizes pores, and controls excess oil.",
    originalPrice: "400.00",
    price: "390.00",
    discountPercentage: 3,
    sku: "ALITE-CFW-140G",
    category: "face-care" as const,
    stock: 40,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/charcoal_face_wash_140g.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Vitamin C Brightening Serum 30ml | Glowing Skin | Dark Spot Reduction",
    description: "Brightening serum with Vitamin C that reduces dark spots and gives glowing skin.",
    originalPrice: "600.00",
    price: "580.00",
    discountPercentage: 3,
    sku: "ALITE-VCBS-30ML",
    category: "face-care" as const,
    stock: 25,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/vitamin_c_serum_30ml.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Sunscreen SPF 50+ | UVA/UVB Protection | Non-Greasy | Water Resistant",
    description: "High protection sunscreen with SPF 50+ that protects against UVA and UVB rays. Non-greasy and water resistant.",
    originalPrice: "450.00",
    price: "435.00",
    discountPercentage: 3,
    sku: "ALITE-SPF50-50ML",
    category: "face-care" as const,
    stock: 50,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/sunscreen_spf50_50ml.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Hydrating Face Mask | Moisturizing | Nourishing | Glowing Skin",
    description: "Hydrating face mask that moisturizes and nourishes skin for a healthy glow.",
    originalPrice: "350.00",
    price: "340.00",
    discountPercentage: 3,
    sku: "ALITE-HFM-100G",
    category: "face-care" as const,
    stock: 30,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/hydrating_face_mask_100g.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Body Lotion 200ml | Moisturizing | Nourishing | Smooth Skin",
    description: "Rich body lotion that moisturizes and nourishes skin, leaving it smooth and soft.",
    originalPrice: "300.00",
    price: "290.00",
    discountPercentage: 3,
    sku: "ALITE-BL-200ML",
    category: "body-care" as const,
    stock: 45,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/body_lotion_200ml.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Foot Cream 50gm | Cracked Heels | Dry Feet | Soft & Smooth",
    description: "Intensive foot cream that treats cracked heels and dry feet for soft, smooth skin.",
    originalPrice: "250.00",
    price: "240.00",
    discountPercentage: 4,
    sku: "ALITE-FC-50GM",
    category: "body-care" as const,
    stock: 35,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/foot_cream_50gm.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Hand Cream 50gm | Dry Hands | Nourishing | Soft Hands",
    description: "Nourishing hand cream that treats dry hands and keeps them soft and smooth.",
    originalPrice: "200.00",
    price: "195.00",
    discountPercentage: 3,
    sku: "ALITE-HC-50GM",
    category: "body-care" as const,
    stock: 40,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/hand_cream_50gm.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Complete Skincare Combo | Face Wash + Gel + Cream | Complete Acne Solution",
    description: "Complete skincare combo with face wash, gel, and cream for comprehensive acne treatment.",
    originalPrice: "1200.00",
    price: "1150.00",
    discountPercentage: 4,
    sku: "ALITE-COMBO-COMPLETE",
    category: "combo" as const,
    stock: 15,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/complete_skincare_combo.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Face Toner 100ml | Pore Tightening | Oil Control | Refreshing",
    description: "Refreshing face toner that tightens pores and controls oil for a matte finish.",
    originalPrice: "350.00",
    price: "340.00",
    discountPercentage: 3,
    sku: "ALITE-FT-100ML",
    category: "face-care" as const,
    stock: 30,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/face_toner_100ml.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Under Eye Cream 20gm | Dark Circles | Puffiness | Brightening",
    description: "Targeted under eye cream that reduces dark circles and puffiness for brighter eyes.",
    originalPrice: "400.00",
    price: "385.00",
    discountPercentage: 4,
    sku: "ALITE-UEC-20GM",
    category: "face-care" as const,
    stock: 25,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/under_eye_cream_20gm.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Lip Balm 10gm | Moisturizing | Nourishing | Soft Lips",
    description: "Moisturizing lip balm that nourishes and keeps lips soft and smooth.",
    originalPrice: "150.00",
    price: "145.00",
    discountPercentage: 3,
    sku: "ALITE-LB-10GM",
    category: "face-care" as const,
    stock: 60,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/lip_balm_10gm.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Body Scrub 200gm | Exfoliating | Smooth Skin | Dead Skin Removal",
    description: "Exfoliating body scrub that removes dead skin cells for smooth, glowing skin.",
    originalPrice: "400.00",
    price: "385.00",
    discountPercentage: 4,
    sku: "ALITE-BS-200GM",
    category: "body-care" as const,
    stock: 35,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/body_scrub_200gm.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Shower Gel 250ml | Refreshing | Moisturizing | Clean Skin",
    description: "Refreshing shower gel that cleanses and moisturizes skin for a fresh feeling.",
    originalPrice: "300.00",
    price: "290.00",
    discountPercentage: 3,
    sku: "ALITE-SG-250ML",
    category: "body-care" as const,
    stock: 50,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/shower_gel_250ml.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Face Cleansing Oil 100ml | Deep Cleansing | Makeup Removal | Oil Control",
    description: "Deep cleansing oil that removes makeup and impurities while controlling excess oil.",
    originalPrice: "450.00",
    price: "435.00",
    discountPercentage: 3,
    sku: "ALITE-FCO-100ML",
    category: "face-care" as const,
    stock: 28,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/face_cleansing_oil_100ml.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Night Repair Cream 50gm | Anti-Aging | Repairing | Nourishing",
    description: "Night repair cream that repairs skin damage and provides anti-aging benefits.",
    originalPrice: "550.00",
    price: "530.00",
    discountPercentage: 4,
    sku: "ALITE-NRC-50GM",
    category: "face-care" as const,
    stock: 22,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/night_repair_cream_50gm.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Day Cream SPF 30 | Moisturizing | Sun Protection | Glowing Skin",
    description: "Day cream with SPF 30 that moisturizes and protects skin from sun damage.",
    originalPrice: "500.00",
    price: "485.00",
    discountPercentage: 3,
    sku: "ALITE-DC-SPF30-50GM",
    category: "face-care" as const,
    stock: 32,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/day_cream_spf30_50gm.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Face Pack 100gm | Detoxifying | Brightening | Glowing Skin",
    description: "Detoxifying face pack that brightens skin and gives a natural glow.",
    originalPrice: "350.00",
    price: "340.00",
    discountPercentage: 3,
    sku: "ALITE-FP-100GM",
    category: "face-care" as const,
    stock: 38,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/face_pack_100gm.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Body Butter 150gm | Intensive Moisturizing | Dry Skin | Smooth Skin",
    description: "Intensive body butter that deeply moisturizes dry skin for smooth, soft texture.",
    originalPrice: "400.00",
    price: "385.00",
    discountPercentage: 4,
    sku: "ALITE-BB-150GM",
    category: "body-care" as const,
    stock: 30,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/body_butter_150gm.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Face & Body Combo | Complete Skincare Routine | Face Wash + Body Lotion",
    description: "Complete skincare combo with face wash and body lotion for daily care routine.",
    originalPrice: "600.00",
    price: "580.00",
    discountPercentage: 3,
    sku: "ALITE-COMBO-FB",
    category: "combo" as const,
    stock: 18,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/face_body_combo.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Acne Care Combo | Face Wash + Gel + Cream | Complete Solution",
    description: "Complete acne care combo with face wash, gel, and cream for effective treatment.",
    originalPrice: "1400.00",
    price: "1350.00",
    discountPercentage: 4,
    sku: "ALITE-COMBO-ACNE-CARE",
    category: "combo" as const,
    stock: 12,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/acne_care_combo.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Glow Combo | Face Wash + Scrub + Cream | Radiant Skin",
    description: "Glow combo with face wash, scrub, and cream for radiant, glowing skin.",
    originalPrice: "1000.00",
    price: "970.00",
    discountPercentage: 3,
    sku: "ALITE-COMBO-GLOW",
    category: "combo" as const,
    stock: 20,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/glow_combo.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Anti-Aging Combo | Serum + Cream + Eye Cream | Youthful Skin",
    description: "Anti-aging combo with serum, cream, and eye cream for youthful, radiant skin.",
    originalPrice: "1500.00",
    price: "1450.00",
    discountPercentage: 3,
    sku: "ALITE-COMBO-ANTIAGING",
    category: "combo" as const,
    stock: 10,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/anti_aging_combo.jpg",
    isBestSeller: false,
  },
  {
    name: "Alite Men's Skincare Combo | Face Wash + Gel + Cream | Complete Care",
    description: "Complete men's skincare combo with face wash, gel, and cream for daily care.",
    originalPrice: "1100.00",
    price: "1060.00",
    discountPercentage: 4,
    sku: "ALITE-COMBO-MENS",
    category: "combo" as const,
    stock: 15,
    imageUrl: "https://www.aliteskincare.in/cdn/shop/files/mens_skincare_combo.jpg",
    isBestSeller: false,
  },
];

async function seed() {
  try {
    console.log("🌱 Starting to seed products...");

    // Clear existing products (optional - comment out if you want to keep existing data)
    // await db.delete(products);

    // Insert products
    for (const product of productData) {
      try {
        await db.insert(products).values(product);
        console.log(`✅ Seeded: ${product.name.substring(0, 50)}...`);
      } catch (error: any) {
        if (error.code === "ER_DUP_ENTRY") {
          console.log(`⏭️  Skipped (duplicate): ${product.name.substring(0, 50)}...`);
        } else {
          console.error(`❌ Error seeding ${product.name}:`, error);
        }
      }
    }

    console.log(`\n✨ Successfully seeded ${productData.length} products!`);
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
}

// Run seeder if this file is executed directly
if (import.meta.main) {
  seed();
}
